version: "3.8"

services:
  # ──────────────────────────────
  # PostgreSQL (unchanged)
  # ──────────────────────────────
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contacts
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]

  # ──────────────────────────────
  # Redis – new cache layer
  # ──────────────────────────────
  redis:
    image: redis:7-alpine          # light & recent
    restart: always
    ports:
      - "6379:6379"                # expose only if you want host access
    command: ["redis-server", "--save", ""]  # no RDB persistence → pure cache
    # volumes:                     # uncomment if you *want* persistence
    #   - redis_data:/data

  # ──────────────────────────────
  # FastAPI app
  # ──────────────────────────────
  web:
    build: .
    command: >
      sh -c "sleep 5 && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    env_file:
      - .env                       # include REDIS_* vars there
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  postgres_data:
  # redis_data:                   # only if you enable persistence above